name: app_grupohdi
description: Aplicacao mobile GrupoHDI

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.5
  http: ^0.13.4
  url_launcher: ^6.1.5
  flutter_local_notifications: ^9.7.0
  workmanager: ^0.5.0
  settings_ui: ^2.0.2
  #remover a dependencia de settigns
  flutter_settings_screens: ^0.2.2+1
  provider: ^5.0.0
  shared_preferences: ^2.0.15

  curved_navigation_bar: ^1.0.3
  flutter_launcher_icons: ^0.9.3
  timezone: ^0.8.0
  intl: ^0.17.0
  slide_digital_clock: any
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1

flutter:
  assets:
    - assets/
  uses-material-design: true

flutter_icons:
  image_path: "icon/icon.png"
  android: true
  ios: false